"""empty message

Revision ID: 464de491e043
Revises: ae47caef160e
Create Date: 2023-09-27 14:22:07.273862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464de491e043'
down_revision = 'ae47caef160e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('order_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('order_time')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
