"""empty message

Revision ID: b619e1f4ba2b
Revises: d73702c9a0f6
Create Date: 2023-09-27 11:36:01.052962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b619e1f4ba2b'
down_revision = 'd73702c9a0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('order_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_time', sa.DATETIME(), nullable=False))

    # ### end Alembic commands ###
